apiVersion: apps/v1
kind: Deployment
metadata:
  name: mean-angular
  labels:
    app: mean-angular
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mean-angular
  template:
    metadata:
      labels:
        app: mean-angular
    spec:
      containers:
      - image: khaledklai/mean-angular:0.2
        name: mean-angular
        env:
          - name: EXPRESS_HOST
            value: "mean-express"
          - name: EXPRESS_PORT
            value: "3000"
